## Imports

In [1]:
import os
import pandas as pd
import geopandas as gpd
from zipfile import ZipFile

from pathlib import Path
from sqlalchemy import create_engine, text
from geoalchemy2 import Geometry

In [2]:
DATA_DIR = Path("../data/JC")

citibike_path = DATA_DIR / "JC2025.csv"
weather_path = DATA_DIR / "jersey_weather_2025.csv"
neighborhood_path = DATA_DIR / "jersey-city-neighborhoods.geojson"

## Database Connection

In [3]:
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_HOST = os.getenv("DB_HOST", "localhost")
DB_PORT = os.getenv("DB_PORT", "5432")
DB_NAME = os.getenv("DB_NAME")

DATABASE_URL = (
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}"
    f"@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)


DATABASE_URL

'postgresql+psycopg2://postgres:password@localhost:5432/citibike'

In [4]:
## Engine Creation
engine = create_engine(DATABASE_URL)

engine

Engine(postgresql+psycopg2://postgres:***@localhost:5432/citibike)

### Test Connection

In [5]:
with engine.connect() as connection:
    result = connection.execute(text("SELECT version();"))
    print(result.fetchone()[0])

PostgreSQL 17.0 (Debian 17.0-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

### Test PostGIS Extension

In [6]:
with engine.connect() as connection:
    result = connection.execute(text("SELECT PostGIS_Version();"))
    print(result.fetchone()[0])

3.4 USE_GEOS=1 USE_PROJ=1 USE_STATS=1

## Citibike to PostgreSQL

### Reading the data

In [7]:
citibike_df = pd.read_csv(citibike_path)

citibike_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,9F734BE1BFC45FF4,electric_bike,2025-11-18 18:34:14.943,2025-11-18 18:47:33.391,Glenwood Ave,JC094,West Side Ave & Stegman Pkwy,JC131,40.727551,-74.071061,40.710870,-74.093680,member
1,B6C773B13AC0E465,classic_bike,2025-11-26 16:29:15.513,2025-11-26 16:43:45.235,Glenwood Ave,JC094,West Side Ave & Stegman Pkwy,JC131,40.727551,-74.071061,40.710870,-74.093680,member
2,C300465AA158280F,electric_bike,2025-11-04 22:31:58.010,2025-11-04 22:38:57.017,Bloomfield St & 15 St,HB203,Marshall St & 2 St,HB408,40.754530,-74.026580,40.740802,-74.042521,member
3,31A424FC97C8AAFB,classic_bike,2025-11-08 06:51:57.424,2025-11-08 06:57:45.627,Clinton St & 7 St,HB303,Marshall St & 2 St,HB408,40.745420,-74.033320,40.740802,-74.042521,member
4,08C5EA04CB1FDC57,classic_bike,2025-11-24 20:31:21.758,2025-11-24 20:38:01.261,Clinton St & 7 St,HB303,Marshall St & 2 St,HB408,40.745420,-74.033320,40.740802,-74.042521,member

In [8]:
print(citibike_df.columns)
citibike_df.info()

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 1002704 entries, 0 to 1002703
Data columns (total 13 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   ride_id             1002704 non-null  str
 1   rideable_type       1002704 non-null  str
 2   started_at          1002704 non-null  str
 3   ended_at            1002704 non-null  str
 4   start_station_name  1002701 non-null  str
 5   start_station_id    1002701 non-null  str
 6   end_station_name    999469 non-null   str
 7   end_station_id      998307 non-null   str
 8   start_lat           1002702 non-null  float64
 9   start_lng           1002702 non-null  float64
 10  end_lat             999260 non-null   float64
 11  end_lng             999260 non-null   float64
 12  member_casual       1002704 non-null  str
dtypes: float64(4), str(9)
memory usage: 99.5 MB

In [9]:
# Cleaning the Data
citibike_df["started_at"] = pd.to_datetime(
    citibike_df["started_at"],
    errors="coerce"
)

citibike_df["ended_at"] = pd.to_datetime(
    citibike_df["ended_at"],
    errors="coerce"
)

In [10]:
citibike_df["ride_date"] = citibike_df["started_at"].dt.date

citibike_df["ride_date"] = pd.to_datetime(
    citibike_df["ride_date"],
    errors="coerce"
)

citibike_df[
    [
        "ride_id",
        "started_at",
        "ended_at",
        "ride_date"
    ]
].head()

            ride_id              started_at                ended_at  ride_date
0  9F734BE1BFC45FF4 2025-11-18 18:34:14.943 2025-11-18 18:47:33.391 2025-11-18
1  B6C773B13AC0E465 2025-11-26 16:29:15.513 2025-11-26 16:43:45.235 2025-11-26
2  C300465AA158280F 2025-11-04 22:31:58.010 2025-11-04 22:38:57.017 2025-11-04
3  31A424FC97C8AAFB 2025-11-08 06:51:57.424 2025-11-08 06:57:45.627 2025-11-08
4  08C5EA04CB1FDC57 2025-11-24 20:31:21.758 2025-11-24 20:38:01.261 2025-11-24

### Writing CitiBike data to PostgreSQL Database

In [12]:
citibike_df.to_sql(
    name="jersey_city",
    con=engine,
    if_exists="replace",
    index=False,
    chunksize=50_000,
    method="multi"
)

1002704

#### Check rows in Pandas

In [13]:
query = """
SELECT
    *
FROM jersey_city
LIMIT 10;
"""

pd.read_sql(
    query,
    con=engine
)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_date
0,9F734BE1BFC45FF4,electric_bike,2025-11-18 18:34:14.943,2025-11-18 18:47:33.391,Glenwood Ave,JC094,West Side Ave & Stegman Pkwy,JC131,40.727551,-74.071061,40.710870,-74.093680,member,2025-11-18
1,B6C773B13AC0E465,classic_bike,2025-11-26 16:29:15.513,2025-11-26 16:43:45.235,Glenwood Ave,JC094,West Side Ave & Stegman Pkwy,JC131,40.727551,-74.071061,40.710870,-74.093680,member,2025-11-26
2,C300465AA158280F,electric_bike,2025-11-04 22:31:58.010,2025-11-04 22:38:57.017,Bloomfield St & 15 St,HB203,Marshall St & 2 St,HB408,40.754530,-74.026580,40.740802,-74.042521,member,2025-11-04
3,31A424FC97C8AAFB,classic_bike,2025-11-08 06:51:57.424,2025-11-08 06:57:45.627,Clinton St & 7 St,HB303,Marshall St & 2 St,HB408,40.745420,-74.033320,40.740802,-74.042521,member,2025-11-08
4,08C5EA04CB1FDC57,classic_bike,2025-11-24 20:31:21.758,2025-11-24 20:38:01.261,Clinton St & 7 St,HB303,Marshall St & 2 St,HB408,40.745420,-74.033320,40.740802,-74.042521,member,2025-11-24
5,FE738136C74EA7C0,electric_bike,2025-11-23 14:39:45.031,2025-11-23 14:43:32.044,Clinton St & 7 St,HB303,Marshall St & 2 St,HB408,40.745420,-74.033320,40.740802,-74.042521,member,2025-11-23
6,EFD5AB3E138908E4,electric_bike,2025-11-19 21:08:33.665,2025-11-19 21:14:22.866,Clinton St & 7 St,HB303,Marshall St & 2 St,HB408,40.745420,-74.033320,40.740802,-74.042521,member,2025-11-19
7,A45C71BC39881445,electric_bike,2025-11-11 15:29:51.785,2025-11-11 15:33:44.683,Clinton St & 7 St,HB303,Marshall St & 2 St,HB408,40.745420,-74.033320,40.740802,-74.042521,member,2025-11-11
8,33FE83F576FDA580,electric_bike,2025-11-08 13:11:03.012,2025-11-08 13:15:13.476,Clinton St & 7 St,HB303,Marshall St & 2 St,HB408,40.745420,-74.033320,40.740802,-74.042521,member,2025-11-08
9,29D92C83FFD009F2,electric_bike,2025-11-14 18:39:54.678,2025-11-14 18:44:18.044,Clinton St & 7 St,HB303,Marshall St & 2 St,HB408,40.745420,-74.033320,40.740802,-74.042521,member,2025-11-14

## Load Weather Data

In [11]:
weather_df = pd.read_csv(weather_path)

weather_df.head()

,2m_max,2m_min,2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max,date
0,10.9,3.9,7.4,4.5,4.5,0.0,23.2,2025-01-01
1,5.4,0.3,2.6,0.0,0.0,0.0,25.1,2025-01-02
2,3.2,-1.9,0.4,0.0,0.0,0.0,17.1,2025-01-03
3,-0.1,-2.7,-1.4,0.0,0.0,0.0,26.1,2025-01-04
4,0.3,-3.6,-2.2,0.0,0.0,0.0,19.9,2025-01-05

### Convert Date Column

In [12]:
weather_df["date"] = pd.to_datetime(
    weather_df["date"],
    errors="coerce"
)

weather_df.head()

,2m_max,2m_min,2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max,date
0,10.9,3.9,7.4,4.5,4.5,0.0,23.2,2025-01-01
1,5.4,0.3,2.6,0.0,0.0,0.0,25.1,2025-01-02
2,3.2,-1.9,0.4,0.0,0.0,0.0,17.1,2025-01-03
3,-0.1,-2.7,-1.4,0.0,0.0,0.0,26.1,2025-01-04
4,0.3,-3.6,-2.2,0.0,0.0,0.0,19.9,2025-01-05

### Write Weather Data to Database

In [16]:
#| echo: true

weather_df.to_sql(
    name="jersey_weather",
    con=engine,
    if_exists="replace",
    index=False
)

365

In [17]:
query = """
SELECT
    *
FROM jersey_weather
LIMIT 10;
"""

pd.read_sql(
    query,
    con=engine
)

,2m_max,2m_min,2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max,date
0,10.9,3.9,7.4,4.5,4.5,0.00,23.2,2025-01-01
1,5.4,0.3,2.6,0.0,0.0,0.00,25.1,2025-01-02
2,3.2,-1.9,0.4,0.0,0.0,0.00,17.1,2025-01-03
3,-0.1,-2.7,-1.4,0.0,0.0,0.00,26.1,2025-01-04
4,0.3,-3.6,-2.2,0.0,0.0,0.00,19.9,2025-01-05
5,-1.5,-4.4,-2.3,1.7,0.0,1.19,16.7,2025-01-06
6,-3.0,-8.7,-5.2,0.0,0.0,0.00,29.9,2025-01-07
7,-2.5,-6.6,-4.3,0.0,0.0,0.00,25.4,2025-01-08
8,-1.5,-6.8,-4.2,0.0,0.0,0.00,29.0,2025-01-09
9,3.3,-3.8,-0.9,0.0,0.0,0.00,22.5,2025-01-10

## Load Neighborhood GeoJSON as Spatial Table

### Read GeoJSON with GeoPandas

In [13]:
neighborhood_gdf = gpd.read_file(neighborhood_path)

neighborhood_gdf.head()

,cartodb_id,area_sq_ft,acres,area,neighborhood,color,lon,lat,area_sq_km,estimated_neighborhood_population,population_density_per_sq_km,nbhd_population,geometry
0,38,411601381.8,9449.068,Greenville,Port Liberte,NaN,-74.074540,40.694202,38.23902,5739.716981,150.10105,5739.716981,"POLYGON ((-74.06862 40.70098, -74.06808 40.696..."
1,52,411601381.8,9449.068,Bergen-Lafayette,LSP Industrial,NaN,-74.062358,40.699189,38.23902,5739.716981,150.10105,5739.716981,"POLYGON ((-74.06808 40.69684, -74.06862 40.700..."
2,29,411601381.8,9449.068,West Side,Hackensack,NaN,-74.085147,40.735520,38.23902,5739.716981,150.10105,5739.716981,"POLYGON ((-74.07601 40.73822, -74.07781 40.737..."
3,35,411601381.8,9449.068,Bergen-Lafayette,Lafayette,12.0,-74.061279,40.712676,38.23902,5739.716981,150.10105,5739.716981,"POLYGON ((-74.056 40.71735, -74.056 40.71692, ..."
4,51,411601381.8,9449.068,Greenville,Jackson Hill,15.0,-74.085503,40.700791,38.23902,5739.716981,150.10105,5739.716981,"POLYGON ((-74.07561 40.70233, -74.0758 40.7020..."

In [14]:
# Checking the crs of the GeoDataFrame
neighborhood_gdf.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [15]:
neighborhood_gdf.geom_type.value_counts()

Polygon    53
Name: count, dtype: int64

### Write GeoDataFrame to PostGIS

In [21]:
#| echo: true

neighborhood_gdf.to_postgis(
    name="jersey_city_neighborhoods",
    con=engine,
    if_exists="replace",
    index=False
)

In [22]:


query = """
SELECT
    neighborhood,
    ST_GeometryType(geometry) AS geometry_type,
    ST_SRID(geometry) AS srid
FROM jersey_city_neighborhoods
LIMIT 5;
"""

pd.read_sql(
    query,
    con=engine
)

     neighborhood geometry_type  srid
0    Port Liberte    ST_Polygon  4326
1  LSP Industrial    ST_Polygon  4326
2      Hackensack    ST_Polygon  4326
3       Lafayette    ST_Polygon  4326
4    Jackson Hill    ST_Polygon  4326

## Create Station Spatial Table
##### The ride table has start and end coordinates, but we also want a station-level spatial table.

### Create Station Summary

In [16]:
start_stations = citibike_df[
    [
        "ride_id",
        "start_station_id",
        "start_station_name",
        "start_lat",
        "start_lng"
    ]
].copy()

start_stations = start_stations.rename(
    columns={
        "start_station_id": "station_id",
        "start_station_name": "station_name",
        "start_lat": "lat",
        "start_lng": "lng"
    }
)

start_stations["activity_type"] = "departure"

In [17]:
end_stations = citibike_df[
    [
        "ride_id",
        "end_station_id",
        "end_station_name",
        "end_lat",
        "end_lng"
    ]
].copy()

end_stations = end_stations.rename(
    columns={
        "end_station_id": "station_id",
        "end_station_name": "station_name",
        "end_lat": "lat",
        "end_lng": "lng"
    }
)

end_stations["activity_type"] = "arrival"

In [18]:
station_activity_long = pd.concat(
    [
        start_stations,
        end_stations
    ],
    ignore_index=True
)

station_activity_long = station_activity_long.dropna(
    subset=[
        "station_id",
        "station_name",
        "lat",
        "lng"
    ]
)

In [19]:
station_activity_agg = (
    station_activity_long
    .groupby(
        [
            "station_id",
            "station_name",
            "lat",
            "lng",
            "activity_type"
        ],
        as_index=False
    )
    .agg(
        number_of_rides=("ride_id", "count")
    )
)

In [27]:
station_summary = (
    station_activity_agg
    .pivot_table(
        index=[
            "station_id",
            "station_name",
            "lat",
            "lng"
        ],
        columns="activity_type",
        values="number_of_rides",
        fill_value=0
    )
    .reset_index()
)

station_summary.columns.name = None

station_summary = station_summary.rename(
    columns={
        "departure": "total_departures",
        "arrival": "total_arrivals"
    }
)

if "total_departures" not in station_summary.columns:
    station_summary["total_departures"] = 0

if "total_arrivals" not in station_summary.columns:
    station_summary["total_arrivals"] = 0

station_summary["total_activity"] = (
    station_summary["total_departures"] +
    station_summary["total_arrivals"]
)

station_summary["net_departures"] = (
    station_summary["total_departures"] -
    station_summary["total_arrivals"]
)

station_summary = station_summary.sort_values(
    "total_activity",
    ascending=False
).reset_index(drop=True)

station_summary.head()

,station_id,station_name,lat,lng,total_arrivals,total_departures,total_activity,net_departures
0,JC115,Grove St PATH,40.719410,-74.043090,47744.0,45121.0,92865.0,-2623.0
1,HB101,Hoboken Terminal - Hudson St & Hudson Pl,40.735938,-74.030305,26638.0,25964.0,52602.0,-674.0
2,JC009,Hamilton Park,40.727596,-74.044247,22347.0,22311.0,44658.0,-36.0
3,HB106,River St & Newark St,40.736722,-74.029007,22113.0,21489.0,43602.0,-624.0
4,JC066,Newport PATH,40.727224,-74.033759,20698.0,20704.0,41402.0,6.0

### Convert Station Summary to GeoDataFrame

In [28]:
station_gdf = gpd.GeoDataFrame(
    station_summary,
    geometry=gpd.points_from_xy(
        station_summary["lng"],
        station_summary["lat"]
    ),
    crs="EPSG:4326"
)

station_gdf.head()

,station_id,station_name,lat,lng,total_arrivals,total_departures,total_activity,net_departures,geometry
0,JC115,Grove St PATH,40.719410,-74.043090,47744.0,45121.0,92865.0,-2623.0,POINT (-74.04309 40.71941)
1,HB101,Hoboken Terminal - Hudson St & Hudson Pl,40.735938,-74.030305,26638.0,25964.0,52602.0,-674.0,POINT (-74.0303 40.73594)
2,JC009,Hamilton Park,40.727596,-74.044247,22347.0,22311.0,44658.0,-36.0,POINT (-74.04425 40.7276)
3,HB106,River St & Newark St,40.736722,-74.029007,22113.0,21489.0,43602.0,-624.0,POINT (-74.02901 40.73672)
4,JC066,Newport PATH,40.727224,-74.033759,20698.0,20704.0,41402.0,6.0,POINT (-74.03376 40.72722)

### Write Station Points to PostGIS

In [30]:
station_gdf.to_postgis(
    name="jc_2025_stations",
    con=engine,
    if_exists="replace",
    index=False
)

### Check Station Spatial Table

In [31]:


query = """
SELECT
    station_id,
    station_name,
    total_activity,
    ST_GeometryType(geometry) AS geometry_type,
    ST_SRID(geometry) AS srid
FROM jc_2025_stations
LIMIT 5;
"""

pd.read_sql(
    query,
    con=engine
)

,station_id,station_name,total_activity,geometry_type,srid
0,JC115,Grove St PATH,92865.0,ST_Point,4326
1,HB101,Hoboken Terminal - Hudson St & Hudson Pl,52602.0,ST_Point,4326
2,JC009,Hamilton Park,44658.0,ST_Point,4326
3,HB106,River St & Newark St,43602.0,ST_Point,4326
4,JC066,Newport PATH,41402.0,ST_Point,4326

## Update Data for 2026

### Imports

In [11]:
from pathlib import Path
from urllib.request import urlretrieve
from urllib.error import HTTPError, URLError
from zipfile import ZipFile

import sys
import os

sys.path.append(os.path.abspath('..'))
from utils import period_iterator, download_jersey_tripdata_zip_and_extract_to_local

import shutil
import glob

### Download and save the 2026 Citibike data

In [14]:
CITIBIKE_INDEX_URL = "https://s3.amazonaws.com/tripdata"
OUTPUT_DIR = "../data/citibike/"

In [27]:
PERIODS = period_iterator(year =["2026"], start_m=0, stop_m=6)
PERIODS

['202601', '202602', '202603', '202604', '202605', '202606']

In [ ]:
output_dir = Path(OUTPUT_DIR)
output_dir.mkdir(exist_ok=True)

download_jersey_tripdata_zip_and_extract_to_local(
    periods=PERIODS,
    base_url=CITIBIKE_INDEX_URL,
    local_path=output_dir
)

In [30]:
shutil.rmtree(output_dir / "__MACOSX")

In [16]:
file_names = glob.glob(f'{output_dir}/*.csv')



dfs = []
cols = []
for file_name in file_names:
    df = pd.read_csv(file_name)
    print(df.columns, 2*"||",len(df.columns))

    cols.append(list(df.columns))
    dfs.append(df)

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13

In [17]:
citibike26_df = pd.concat(dfs, ignore_index=True)
citibike26_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,40FBC7AEEBB220EC,electric_bike,2026-01-11 15:01:01.954,2026-01-11 15:16:57.103,14 St Ferry - 14 St & Shipyard Ln,HB202,Pier 61 at Chelsea Piers,6233.04,40.752961,-74.024353,40.746872,-74.00821,member
1,47FB1CA65D3F7E0F,electric_bike,2026-01-16 11:49:41.364,2026-01-16 11:58:27.291,14 St Ferry - 14 St & Shipyard Ln,HB202,Madison St & 1 St,HB402,40.752961,-74.024353,40.738790,-74.03930,member
2,BFB10DE1E40F3709,electric_bike,2026-01-07 19:55:41.424,2026-01-07 19:59:09.874,Church Sq Park - 5 St & Park Ave,HB601,Madison St & 1 St,HB402,40.742659,-74.032233,40.738790,-74.03930,member
3,F16B896495AAF618,electric_bike,2026-01-24 11:12:10.547,2026-01-24 11:34:42.801,Madison St & 1 St,HB402,Madison St & 1 St,HB402,40.738790,-74.039300,40.738790,-74.03930,member
4,76D77D5F1D491B3C,electric_bike,2026-01-22 20:58:00.602,2026-01-22 21:02:39.088,Clinton St & 7 St,HB303,Madison St & 1 St,HB402,40.745420,-74.033320,40.738790,-74.03930,casual

In [18]:
citibike26_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 415739 entries, 0 to 415738
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             415739 non-null  str
 1   rideable_type       415739 non-null  str
 2   started_at          415739 non-null  str
 3   ended_at            415739 non-null  str
 4   start_station_name  415738 non-null  str
 5   start_station_id    415738 non-null  str
 6   end_station_name    413634 non-null  str
 7   end_station_id      412883 non-null  str
 8   start_lat           415738 non-null  float64
 9   start_lng           415738 non-null  float64
 10  end_lat             412897 non-null  float64
 11  end_lng             412897 non-null  float64
 12  member_casual       415739 non-null  str
dtypes: float64(4), str(9)
memory usage: 41.2 MB

In [19]:
citibike26_df.isna().sum()

ride_id                  0
rideable_type            0
started_at               0
ended_at                 0
start_station_name       1
start_station_id         1
end_station_name      2105
end_station_id        2856
start_lat                1
start_lng                1
end_lat               2842
end_lng               2842
member_casual            0
dtype: int64

#### Converting the date columns to datetime format

In [20]:
# Cleaning the Data
citibike26_df["started_at"] = pd.to_datetime(
    citibike26_df["started_at"],
    errors="coerce"
)

citibike26_df["ended_at"] = pd.to_datetime(
    citibike26_df["ended_at"],
    errors="coerce"
)

In [21]:

citibike26_df["ride_date"] = citibike26_df["started_at"].dt.date

citibike26_df["ride_date"] = pd.to_datetime(
    citibike26_df["ride_date"],
    errors="coerce"
)

citibike26_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_date
0,40FBC7AEEBB220EC,electric_bike,2026-01-11 15:01:01.954,2026-01-11 15:16:57.103,14 St Ferry - 14 St & Shipyard Ln,HB202,Pier 61 at Chelsea Piers,6233.04,40.752961,-74.024353,40.746872,-74.00821,member,2026-01-11
1,47FB1CA65D3F7E0F,electric_bike,2026-01-16 11:49:41.364,2026-01-16 11:58:27.291,14 St Ferry - 14 St & Shipyard Ln,HB202,Madison St & 1 St,HB402,40.752961,-74.024353,40.738790,-74.03930,member,2026-01-16
2,BFB10DE1E40F3709,electric_bike,2026-01-07 19:55:41.424,2026-01-07 19:59:09.874,Church Sq Park - 5 St & Park Ave,HB601,Madison St & 1 St,HB402,40.742659,-74.032233,40.738790,-74.03930,member,2026-01-07
3,F16B896495AAF618,electric_bike,2026-01-24 11:12:10.547,2026-01-24 11:34:42.801,Madison St & 1 St,HB402,Madison St & 1 St,HB402,40.738790,-74.039300,40.738790,-74.03930,member,2026-01-24
4,76D77D5F1D491B3C,electric_bike,2026-01-22 20:58:00.602,2026-01-22 21:02:39.088,Clinton St & 7 St,HB303,Madison St & 1 St,HB402,40.745420,-74.033320,40.738790,-74.03930,casual,2026-01-22

In [22]:
citibike26_df.to_csv("../data/JC/JC2026.csv", index = False)

## Update the code to include the new data for 2026 and save it to a CSV file.

In [23]:
citibike_df = pd.concat([citibike_df, citibike26_df], ignore_index=True)
citibike_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1418443 entries, 0 to 1418442
Data columns (total 14 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   ride_id             1418443 non-null  str
 1   rideable_type       1418443 non-null  str
 2   started_at          1418443 non-null  datetime64[us]
 3   ended_at            1418443 non-null  datetime64[us]
 4   start_station_name  1418439 non-null  str
 5   start_station_id    1418439 non-null  str
 6   end_station_name    1413103 non-null  str
 7   end_station_id      1411190 non-null  str
 8   start_lat           1418440 non-null  float64
 9   start_lng           1418440 non-null  float64
 10  end_lat             1412157 non-null  float64
 11  end_lng             1412157 non-null  float64
 12  member_casual       1418443 non-null  str
 13  ride_date           1418443 non-null  datetime64[s]
dtypes: datetime64[s](1), datetime64[us](2), float64(4), str(7)
memory usage: 151.5 MB

In [24]:
citibike_df.isna().sum()

ride_id                  0
rideable_type            0
started_at               0
ended_at                 0
start_station_name       4
start_station_id         4
end_station_name      5340
end_station_id        7253
start_lat                3
start_lng                3
end_lat               6286
end_lng               6286
member_casual            0
ride_date                0
dtype: int64

In [25]:
citibike_df.to_csv("../data/JC/JC2025_2026.csv", index = False)

In [26]:
shutil.rmtree(output_dir)